### ISSUE TITLE
Drop the `auth` global lock magic.

### ISSUE THREAD

**Issue by jamestalmage** [casetext/fireproof#10]
From the source:

``` js
/*
 * For reasons completely incomprehensible to me, some type of race condition
 * is possible if multiple Fireproof references attempt authentication at the
 * same time, the result of which is one or more of the promises will never
 * resolve.
 * Accordingly, it is necessary that we wrap authentication actions in a
 * global lock. This is accomplished by queuing operations in an array. No, I
 * don't like it any more than you do.
*/
```

I understand the pain-point you are trying to avoid, but this is a bad idea. It masks the intended behavior of the underlying library. 

From the [Firebase docs](https://www.firebase.com/docs/web/api/firebase/authwithcustomtoken.html).

> All Firebase references to the same database share the same authentication status, so if you call `new Firebase("https://.firebaseio.com/"`) twice and call any authentication method on one of them, they will both be authenticated.

If you point your ref's at two different firebase _base_ URL's (`https://firebase1.firebaseio.test`, and `https://firebase2.firebaseio.test`), you should be able to authenticate both of those concurrently without the odd behavior.

You really should not be calling `auth` twice (concurrently) in your code. If you are it is probably an error. The authorization token from the second call will be used to authenticate the first - even if you have created separate ref instances.

If you really want to avoid this behavior, you can use `firebase-copy`, which gives you a new `Firebase` constructors each time, with its own set of global state. In addition to avoiding the `auth` idiosyncrasies that are frustrating you here, it also improves some client side code testing by ensuring async behavior behavior between `ref.set` and `ref.on('value', listener)`

``` js
var firebaseCopy = require('firebase-copy');

var Firebase1 = firebaseCopy();
var Firebase2 = firebaseCopy();

var ref1 = new Firebase1(URL);
var ref2 = new Firebase2(URL);

ref1.on('value', listener1);
ref2.on('value', listener2);

ref1.set(newValue);
// => listener1 will trigger synchronously (before roundtrip to server, potentially triggered twice if write is denied).
// => listener2 will fire once asynchronously (after roundtrip to server. Potentially never triggered if write is denied).
```

I do not recommend `firebase-copy` for production, just testing. 

The global state behavior of Firebase is intentional. It is better to structure your app to deal with those idiosyncrasies directly than trying to hide them.

**Comment by jamestalmage** [comment]
As a potential solution I recommend one of two strategies:

**Option 1**:

Return a promise that updates it's resolution target with each new call to an auth function.

``` js
var promise1 = ref.authWIthCustomToken(...);  // call1
var promise2 = ref.authWithCustomToken(...);  // call2
```
- promise1 get's resolved with token passed to call2
- unless maybe call2 fails?, and rolls back to call1? not sure how firebase behaves here.
- the point is that it should follow the behavior of Firebase. The promise should resolve with whatever the authorization state is.

**Option 2**:

Detect the concurrent auth attempts and just issue a warning. Otherwise do nothing. (`promise1` never resolves).

**Option 3**:

Deprecate and eventually remove Promisification of auth methods.

---

I lean towards Option 2.

We ran into this issue while creating `angular-fire` and we regret proxying and promisifying the auth methods. Auth state does not fit well with the concept of a `Promise`, it changes over time, where a Promise can be resolved exactly once..

**Comment by daguej** [comment]
This actually works around what is likely a bug in the Firebase client.

We do use multiple Firebase endpoints at the same time (ie db1.firebaseio.com and db2.firebaseio.com), and if you try authing both of them at the same time, one of them never resolves.  You must wait until an in-flight auth operation completes before starting a new one.

**Comment by jamestalmage** [comment]
hmm.
Have you brought that up with the firebase folks?
