### ISSUE TITLE
Should fireproof resolve on `then`?

### ISSUE THREAD

**Issue by pschuegr** [casetext/fireproof#12]
First of all, thanks for this library, very nice.

A question:  I have a function call that returns a promise which I resolve with a Fireproof, which I then plan to use to run a `on('child_added')` query or something similar.  However, returning the Fireproof as part of a promise chain means that the `.then` of the Fireproof object gets called, and I end up with a snapshot instead:

```
function getFireproof() {
  return doSomething()
    .then(() => {
      return new Fireproof(new Firebase('firebase.io/whatever'));
    });
}

getFireproof()
  .on('child_added')  //explodes here because it's getting a snapshot val back
  .then(doSomething);
```

Is there a nicer way to do this that I'm missing in the API?  I can get around it by hacking out the `.then` from the Fireproof instance, but that's not ideal.

**Comment by vramana** [comment]
@pschuegr I think you are using on method incorrectly. Read this https://github.com/casetext/fireproof/blob/master/api.md#fireproofoneventtype-callback-cancelcallback-context

**Comment by pschuegr** [comment]
I'm not sure I'm following you.  It's sort of irrelevant whether I call `on` or one of the other methods (set, createUser, etc).  The point is that I can't return the Fireproof object from a promise chain because the `then` method will attempt to get a snapshot of the current url...

```
getFireproof()
  .orderByValue()  //snapshots don't have .orderbyValue
  .limitToLast(maxMessages)
  .on("value");
```

Sorry if I'm being dense.

**Comment by daguej** [comment]
Think of a Fireproof `then` as Firebase `once('value')`.

Using `on(...)` with promises doesn't make sense because promises resolve exactly once.  A promise cannot trigger its `then` function multiple times.

`on('child_added')` is an event listener that we expect to fire many times; we cannot use promises with it.  You need a traditional callback when using `on`:

```
getFireproof().then(function(ref) {
  ref.on('child_added', function(snap) {
    // do stuff here
  });
});
```

**Comment by pschuegr** [comment]
Sorry, I realized I've unintentionally obfuscated my question by not being precise enough with my sample code.  It's not that the `.on('child_added')` breaks because I'm expecting it to return a promise, it's that `.on` does not exist on the object that comes back from the `getFireproof()` function.

```
function getFireproof() {
  return doSomething()
    .then(() => {
      return new Fireproof(new Firebase('firebase.io/whatever'));
    });
}

getFireproof()
  .on('child_added', function() {})  //explodes here because it's getting a snapshot val back
```

**Comment by daguej** [comment]
If you need to return the Fireproof itself, it needs to be wrapped in something that's not a promise.

```
function getFireproof() {
  return doSomething()
    .then(() => {
      return {
        ref: new Fireproof(new Firebase('firebase.io/whatever'))
      };
    });
}

getFireproof().then(function(result) {
  result.ref.on('child_added', function() {});
});
```

**Comment by pschuegr** [comment]
Wow, fast response, thanks.
