### ISSUE TITLE
delete .defer doesn't work

### ISSUE THREAD

**Issue by steida** [casetext/fireproof#15]
please check closed commit, thank you

_ed_: see https://github.com/casetext/fireproof/issues/14#issuecomment-158239530

**Comment by daguej** [comment]
Fireproof isn't throwing on the absence of `defer`, the promise library is.  There's nothing Fireproof can do here.

**Comment by steida** [comment]
Sure you can do something, remove unnecesary non standard defer method. But if you believe it must be there, ok, it's your library and it tells something about approach to code quality. Never mind.
