### ISSUE TITLE
Refs incompatible with async/await

### ISSUE THREAD

**Issue by wescravens** [casetext/fireproof#19]
Returning a ref from an async function seems to break when the promise is awaited.  This is likely do to the `regeneratorRuntime` checking for Promise-like objects being returned from promises so that they are also awaited.  I suppose a temporary work around is to return `myRef._ref` from any async functions so that there isn't a `.then` method.  Could the return from refs look more like the following?:

``` js
let childRef = baseRef.child('child').set('childValue', true);

console.log(childRef);
/* Fireproof {
  _ref: Firebase {...},
  promise: {
    then: function (ok, fail) {...},
    catch: function (err) {...}
  }
} */
```

This should not be picked up my the regeneratorRuntime's since at the top level it doesn't have any promise methods.

**Comment by daguej** [comment]
A Fireproof ref serves as a promise for the value at the ref's location.  In other words, if you return a ref from a function, you're actually returning a promise for the value of some location.  (`.then` is equivalent to `.once('value', ...)`)  This is true whether you're using traditional promises or `async`/`await`.

If you need to return the ref itself, it should be wrapped in something that's not a promise.

```
return { ref: aFireproofRef };
```

See also #12.

**Comment by daguej** [comment]
Also, the return from `.set` is not a `Fireproof` ref, it's just a promise for when your data has been successfully committed to the server.  (It's the [`onComplete` of `Firebase#set`](https://www.firebase.com/docs/web/api/firebase/set.html).)

**Comment by wescravens** [comment]
Thanks for the response.  Here's essentially what I was doing.

``` js
Actions.createPost.listen(async (post) => {
    let [newPostRef, err] = await catchErrors(createPost(post));
    // newPostRef will be undefined since the return of createPost contains the Fireproof prototype as well as the promise prototype the ref can never directly be the resolve of a promise.
    ...
}

async function createPost (post) {
    let newPostRef = postsRef.push(post),
        postId = newPostRef.key();

    await newPostRef;
    await usersRef.child(`${post.creatorUID}/submitted/${postId}`, true);

    return newPostRef;
}

async function catchErrors (promise) {
    try {
        if (typeof promise === 'function') {
            promise = promise();
        }
        let result = await promise;
        return [result, null];
    } catch (err) {
        return [null, err];
    }
}
```

It seems somewhat strange to directly merge a promise instance with an instance of another constructor since it will satisfy the typical "isPromiseLike" check, but is also has methods of another constructor that may be a desired resolve value for the promise.  Thus, it can never be the resolve of a promise, since it will always qualify as a "thenable" value referring to the same promise (which goes against point 2.3.1 of A+ spec as that should cause a rejection with a TypeError).  In this case, the promise resolution procedure will always treat it as a promise (https://promisesaplus.com/#point-45) and never resolve.

Angular's $resource api does something similar to this in which methods return an instance of the `$resource`, but with a `.$promise` property that contains the promise prototype so it will not qualify as a thenable value.  It still provides access to the promise with a clearer separation of concerns between the `$resource` instance and the `$promise` instance.

Your suggestion to wrap the return in an object works, but seems like a strange way to get around this problem compared to typical behavior that is found in similar cases that come up in the jQuery and Angular APIs when dealing with promises.  I would expect a promise to only contain the standard promise methods.

Currently, I am using my own helper methods to easily separate the ref from the promise allowing the refs to be the resolve value of promises.

``` js
Fireproof.prototype.getRef = function () {
    let ref = new Fireproof(this._ref);
    delete ref.then;
    return ref;
};

Fireproof.prototype.promise = function () {
    return {
        then: this.then.bind(this)
    };
};
```

**Comment by wescravens** [comment]
I suppose what I'm getting at that may be a simple addition to Fireproof would be a convenience method to strip off the promise methods.  Since `.push` returns a ref but is also an async operation, merging the `.then` of the promise onto the ref kills the ability to resolve another promise with the ref since it is both a promise and a ref.

It may also be a good idea to make sure that Fireproof's `.then` method follows the same spec as A+ since when I resolve a promise with the new ref/promise from `.push`, it will be returning the already resolved promise, which will cause an attempt to resolve it again, which should throw an error, but doesn't.

**Comment by goldibex** [comment]
Thanks Wes. Would you be willing to file these two items as separate issues
so we can address them separately?

**Comment by wescravens** [comment]
https://github.com/casetext/fireproof/issues/20

**Comment by wescravens** [comment]
https://github.com/casetext/fireproof/issues/21
