### ISSUE TITLE
`catch` missing when blessed

### ISSUE THREAD

**Issue by daguej** [casetext/fireproof#22]
When blessed, the thing returned from Fireproof is not an actual promise, just an object with a `then` that is bound to the blessed library's `then` function.  The object is missing the `catch` method required by [ES6 § 25.4.5.1](http://www.ecma-international.org/ecma-262/6.0/#sec-promise.prototype.catch).

Ideally, Fireproof would return a real promise from the blessed library.  (When un-blessed -- ie using native promises -- it does appear to return real promises.)

I'm pretty sure this is new to 3.1.

**Comment by goldibex** [comment]
The promises returned by Fireproof in the `bless` case are Promises/A+
compliant, not ES6 compliant (https://promisesaplus.com). In general what
we need is to refactor the entire codebase to use native Promise calls and
clean things up that way. But going forward `.bless` is deprecated together
with the whole "defer" model, which is not ES6 either.
