### ISSUE TITLE
Fireproof return variables

### ISSUE THREAD

**Issue by homayeekazim** [casetext/fireproof#26]
Below is the working code to access data form firebase. It uses global variable 'Data' array to send it to the final callback function. But I don't want to declare global variable. So is there anyway I can pass my data to every callbacks after it ? below is the code.

var data = {};

getData('myKey', function(){
 console.log("myCompleteData: "+ data); //both Id and finalData 
});

var getData= function(key,callback) {
    return fireproof.child("data").child(key)
    .then(CUSTOM_getData)
    .then(callback)
}

function CUSTOM_getData(snapshot) {

```
    var id= snapshot.val().id;
    data.id= id;
```

  return {
    then: function(callback) {

```
fireproof.child("otherData").child(data.id)
.then(CUSTOM_getSomethingFromId)
.then(callback)
  }
```

  };
}

function CUSTOM_getSomethingFromId(snapshot) {

```
        var finalData = snapshot.val().finalData;
        data.finalData = finalData;

  return {
    then: function(callback) {

    callback(data);
      }  
  };
```

}

**Comment by KevinGrandon** [comment]
By global do you mean having something on the window object? It doesn't need to be a global, but it needs to be "in scope". You can just have your variable `data` along with all of the callbacks in the same function.

This seems to be more of a question about javascript and promises rather than this library.

**Comment by homayeekazim** [comment]
Yes this wasn't working so I thought I should ask it here. Probably my approach was incorrect. I was able to solve this. Thanks anyways :) 

P.S: I am new to promises.
