### ISSUE TITLE
Doesn't support native promises

### ISSUE THREAD

**Issue by AsaAyers** [casetext/fireproof#4]
Now that `Promise` is standard JavaScript I don't see any reason to fall back to `Q` promises. Native promises are much easier to debug.

**Comment by airdrummingfool** [comment]
There is a pending PR for this in #2 - it's been reviewed but needs a bit of cleanup.

**Comment by goldibex** [comment]
With Fireproof 3.0.0 we now have native promise support. Thanks everyone!
