### ISSUE TITLE
add keywords to package.json

### ISSUE THREAD

**Issue by jamestalmage** [casetext/fireproof#9]
otherwise nobody can find you!

**Comment by urish** [comment]
"firebase" 
"promise" 

anything else?

**Comment by jamestalmage** [comment]
"async"
"Await"
"Yield"
"Promisify"
"Es6"

Excuse the autocaps.

Also, an example showing how to use it with async/await or yield to sell it's virtues for testing

**Comment by urish** [comment]
:+1:
